/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.4-6-g181cfa1008-20260522"
#endif /* AVUTIL_FFVERSION_H */
